language: python
os: linux
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
env:
  - CLICK=7
  - CLICK=8

install:
  - pip install tox-travis

script: tox

# Only py38-click7 runs pytest with coverage and send results to codecov
after_success: |
  if [[ $TRAVIS_PYTHON_VERSION =~ ^3.8 && $CLICK == 7 ]]; then
     pip install codecov
     codecov
  fi

jobs:
  include:
    - { python: 3.8, env: TOXENV=lint }
    - { python: 3.8, env: TOXENV=mypy }
    - { python: 3.8, env: TOXENV=twine }
    - { python: 3.8, env: TOXENV=docs }
