[build-system]
requires = [
  "setuptools >= 80",
  "setuptools-scm >= 8, < 10",
]
build-backend = "setuptools.build_meta"

[project]
name = "cloup"
dynamic = [
  "authors",
  "classifiers",
  "dependencies",
  "description",
  "keywords",
  "license",
  "readme",
  "requires-python",
  "urls",
  "version",
]

[tool.setuptools_scm]
version_file = "cloup/_version.py"
