"""Top-level package for cloup."""

from typing import TYPE_CHECKING

import click as _click

# WARNING: _version.py is generated by hatch-vcs upon package building/installation
from . import _version

__author__ = """Gianluca Gippetto"""
__email__ = "gianluca.gippetto@gmail.com"
__version__ = _version.version
__version_tuple__ = _version.version_tuple

from click import (
    # core
    Argument,
    CommandCollection,
    Parameter,
    ParameterSource,
    # decorators
    confirmation_option,
    custom_version_option,
    help_option,
    make_pass_decorator,
    pass_obj,
    password_option,
    version_option,
    # exceptions
    Abort,
    BadArgumentUsage,
    BadOptionUsage,
    BadParameter,
    ClickException,
    FileError,
    MissingParameter,
    NoSuchCommand,
    NoSuchOption,
    UsageError,
    # formatting
    wrap_text,
    # termui
    clear,
    confirm,
    echo_via_pager,
    edit,
    get_pager_file,
    getchar,
    launch,
    pause,
    progressbar,
    prompt,
    secho,
    style,
    unstyle,
    # types
    BOOL,
    Choice,
    DateTime,
    File,
    FLOAT,
    FloatRange,
    INT,
    IntRange,
    ParamType,
    Path,
    STRING,
    Tuple,
    UNPROCESSED,
    UUID,
    # utils
    echo,
    format_filename,
    get_app_dir,
    open_file,
)

# Click exposes these deprecated names lazily. Mirror that behavior so importing
# Cloup does not emit their deprecation warnings.
if TYPE_CHECKING:
    from click.core import _BaseCommand as BaseCommand
    from click.core import _MultiCommand as MultiCommand
    from click.parser import _OptionParser as OptionParser
    from click.utils import _get_binary_stream as get_binary_stream
    from click.utils import _get_text_stream as get_text_stream
else:
    _deprecated_click_names = {
        "BaseCommand",
        "MultiCommand",
        "OptionParser",
        "get_binary_stream",
        "get_text_stream",
    }

    def __getattr__(name: str) -> object:
        if name in _deprecated_click_names:
            return getattr(_click, name)
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


from . import warnings as warnings
from .styling import (
    HelpTheme,
    Style,
    Color,
)
from .formatting import (
    HelpFormatter,
    HelpSection,
)
from ._context import Context, get_current_context, pass_context
from ._params import ArgumentKwargs, Option, OptionKwargs, argument, option
from ._option_groups import (
    OptionGroup,
    OptionGroupMixin,
    option_group,
)
from ._sections import (
    Section,
    SectionMixin,
)
from ._commands import (
    Command,
    Group,
    command,
    group,
)
from .constraints import (
    ConstraintMixin,
    constrained_params,
    constraint,
)
from .types import dir_path, file_path, path

__all__ = [
    "Abort",
    "Argument",
    "ArgumentKwargs",
    "BOOL",
    "BadArgumentUsage",
    "BadOptionUsage",
    "BadParameter",
    "BaseCommand",
    "Choice",
    "ClickException",
    "Color",
    "Command",
    "CommandCollection",
    "ConstraintMixin",
    "Context",
    "DateTime",
    "FLOAT",
    "File",
    "FileError",
    "FloatRange",
    "Group",
    "HelpFormatter",
    "HelpSection",
    "HelpTheme",
    "INT",
    "IntRange",
    "MissingParameter",
    "MultiCommand",
    "NoSuchCommand",
    "NoSuchOption",
    "Option",
    "OptionGroup",
    "OptionGroupMixin",
    "OptionKwargs",
    "OptionParser",
    "ParamType",
    "Parameter",
    "ParameterSource",
    "Path",
    "STRING",
    "Section",
    "SectionMixin",
    "Style",
    "Tuple",
    "UNPROCESSED",
    "UUID",
    "UsageError",
    "argument",
    "clear",
    "command",
    "confirm",
    "confirmation_option",
    "constrained_params",
    "constraint",
    "custom_version_option",
    "dir_path",
    "echo",
    "echo_via_pager",
    "edit",
    "file_path",
    "format_filename",
    "get_app_dir",
    "get_binary_stream",
    "get_current_context",
    "get_pager_file",
    "get_text_stream",
    "getchar",
    "group",
    "help_option",
    "launch",
    "make_pass_decorator",
    "open_file",
    "option",
    "option_group",
    "pass_context",
    "pass_obj",
    "password_option",
    "path",
    "pause",
    "progressbar",
    "prompt",
    "secho",
    "style",
    "unstyle",
    "version_option",
    "wrap_text",
]
