"""Top-level package for cloup."""
# WARNING: _version.py is generated by setuptools-scm upon package building/installation
from . import _version

__author__ = """Gianluca Gippetto"""
__email__ = 'gianluca.gippetto@gmail.com'
__version__ = _version.version
__version_tuple__ = _version.version_tuple

# flake8: noqa F401
from ._option_groups import (
    GroupedOption, OptionGroup, OptionGroupMixin, option, option_group
)
from ._sections import Section, SectionMixin
from ._commands import Command, Group, MultiCommand, command, group
from .constraints import ConstraintMixin, constraint
